### ISSUE TITLE
Things to Include in the Project/Gameplan

### ISSUE THREAD

**Issue by MichaelDimmitt** [rubyjax/RubyJaxRailsApi#1]
Site Features:
1. submit_a_talk
2. watch previous talks these are youtube links go to the talks:
    - a client will be able to mark what talks they have seen, have liked, have disliked.
    - should be similar to the "watch" button on these conference talks: https://2023.elixirconf.com/schedule#Wednesday:~:text=Palm%20E-,Wednesday,-7%3A30%20%2D%208

**Comment by MichaelDimmitt** [comment]
### Things that are easy and free
1) Homepage
2) Slack 
- link to the slack
3) Meetup page link ... but also links to future / past meetups. 

### components of previous application that are gotten for free:
1) mobile responsiveness.
2) past videos
3) submit a talk
4) 

### Not free stuff:
1) submit_a_talk; requires a database.
2) forum ... not sure how much we want built out.

**Comment by MichaelDimmitt** [comment]
discuss the job template ... from paris.rb

**questions / random comments**
1) Postman investigation on pre-existing project and building out new api features.
2) List of Features built via API's and not via API
3) Reorganize the list of all features in terms of priority from right to left.
4) Do we want admins logging into the site ... to add information or just via API?
5) 
6)

**Comment by 444c43** [comment]
this appears more of a brainstorm than ticket; closing.
