### ISSUE TITLE
limit titles and description for talks (beginner)

### ISSUE THREAD

**Issue by 444c43** [rubyjax/RubyJaxRailsApi#6]
titles should be a maximum of 10 full words. descriptions should be limited to 200 full words.

add these restrictions to prevent submissions greater than those amounts, and provide a clear error message in the response.

**Comment by murjax** [comment]
Reference article for creating custom validations. https://hackernoon.com/performing-custom-validations-in-rails-an-example-9a373e807144

**Comment by murjax** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet condimentum tortor. Nam sollicitudin.

**Comment by murjax** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc et efficitur odio. Praesent ut tincidunt purus. Pellentesque imperdiet erat est, quis fringilla libero ornare et. Aliquam erat volutpat. Fusce lacinia arcu et finibus lobortis. Nulla convallis ultrices imperdiet. Maecenas bibendum at ligula at pretium. Phasellus ultrices elementum venenatis. Mauris pulvinar luctus orci. Morbi et pretium nunc.

Sed lobortis, risus vitae faucibus tristique, ex nisi molestie nisi, in pharetra nisl lacus vel neque. Fusce finibus eu ante ut sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec semper libero dignissim, placerat arcu finibus, rutrum ligula. Praesent maximus eu orci eget rutrum. Maecenas lorem odio, iaculis vitae facilisis non, luctus ac ipsum. Integer in libero sapien. Aliquam erat volutpat. Nunc vel urna ultricies, feugiat sem volutpat, tincidunt odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam velit nibh, aliquet ornare imperdiet mollis, bibendum at nisl. Maecenas non urna commodo, faucibus nunc venenatis, placerat ipsum. Nunc nulla diam, accumsan at pretium sed, faucibus vitae orci.

Nunc blandit, nisl vitae pretium venenatis, tellus nibh venenatis dolor, eu egestas tortor mauris vel mi. In convallis eget nisl ut gravida. Morbi nec scelerisque eros, id aliquet quam. Aliquam fermentum egestas convallis. Proin sed elementum tellus, ac scelerisque tortor. Nunc eleifend bibendum magna, eu aliquam enim scelerisque ut. Nullam suscipit, augue ac sollicitudin luctus, purus felis sollicitudin sem, sit amet suscipit ante diam sit amet purus. Sed metus dolor, pulvinar a risus quis, fermentum semper odio. Praesent scelerisque quis dolor.
