### ISSUE TITLE
create 'reset password' endpoint (beginner)

### ISSUE THREAD

**Issue by 444c43** [rubyjax/RubyJaxRailsApi#8]
```POST /reset-password		Reset```

create an endpoint for users to submit a password reset request. this issue should provide a simple response back to the user such as, "An email has been sent."

this issue does not actually reset the email, or send a mailer. this only handles a request and response.

**Comment by brydave** [comment]
@mwoods79 @jkelkar @brydave

**Comment by brydave** [comment]
#16
